package io.github.psd2live.ui.components

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.LinearProgressIndicator
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.awt.ComposeWindow
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import io.github.psd2live.i18n.tr
import io.github.psd2live.ui.state.PSD2LiveState
import io.github.psd2live.ui.state.PSD2LiveViewModel
import io.github.psd2live.ui.theme.LocalToolColors
import io.github.psd2live.ui.theme.LocalToolTypography
import io.github.psd2live.ui.utils.NativeFilePicker
import java.nio.file.Path

@Composable
fun ExportPsdDialog(
	state: PSD2LiveState,
	viewModel: PSD2LiveViewModel,
	window: ComposeWindow? = null,
) {
	if (!state.showExportPsdDialog) return
	val colors = LocalToolColors.current
	val typography = LocalToolTypography.current

	val analysis = state.analysis ?: return
	val sourcePath = state.loadedInputPath ?: state.inputPath
	val sourceFile = remember(sourcePath) { runCatching { Path.of(sourcePath) }.getOrNull() }
	val sourceBaseName = remember(sourceFile) {
		sourceFile?.fileName?.toString()?.substringBeforeLast('.') ?: "model"
	}
	val sourceParentDir = remember(sourceFile) {
		sourceFile?.parent?.toString()
	}

	var selectedScale by remember(state.textureUpscale.scale) {
		mutableStateOf(if (state.textureUpscale.scale in listOf(1, 2, 4)) state.textureUpscale.scale else 1)
	}
	var includeGenerated by remember { mutableStateOf(true) }

	fun computeDefaultFileName(scale: Int): String {
		return if (scale > 1) "${sourceBaseName}_upscaled_${scale}x.psd" else "${sourceBaseName}_export.psd"
	}

	var targetPathString by remember(sourceBaseName, selectedScale) {
		val fileName = computeDefaultFileName(selectedScale)
		val initial = if (sourceParentDir != null) Path.of(sourceParentDir, fileName).toString() else fileName
		mutableStateOf(initial)
	}

	val isExporting = state.isExportingPsd
	val canvasW = analysis.source.widthPx * selectedScale
	val canvasH = analysis.source.heightPx * selectedScale
	val layerCount = if (includeGenerated) analysis.layers.size else analysis.source.layers.size

	Box(
		modifier = Modifier
			.fillMaxSize()
			.background(Color(0x99000000))
			.clickable(enabled = !isExporting) { viewModel.closeExportPsdDialog() },
		contentAlignment = Alignment.Center,
	) {
		Column(
			modifier = Modifier
				.width(520.dp)
				.background(colors.panelBackground, RoundedCornerShape(8.dp))
				.border(BorderStroke(1.dp, colors.border), RoundedCornerShape(8.dp))
				.clickable(enabled = false) {}
				.padding(16.dp),
			verticalArrangement = Arrangement.spacedBy(12.dp),
		) {
			// Header
			Row(
				modifier = Modifier.fillMaxWidth(),
				verticalAlignment = Alignment.CenterVertically,
				horizontalArrangement = Arrangement.SpaceBetween,
			) {
				Row(
					verticalAlignment = Alignment.CenterVertically,
					horizontalArrangement = Arrangement.spacedBy(8.dp),
				) {
					Text(
						text = tr("exportPsd.title"),
						style = typography.title.copy(fontSize = 13.5.sp, fontWeight = FontWeight.Bold),
						color = colors.textPrimary,
					)
					if (isExporting) {
						Box(
							modifier = Modifier
								.clip(RoundedCornerShape(4.dp))
								.background(Color(0xFF1B4D3E))
								.border(BorderStroke(1.dp, Color(0xFF4EC9B0)), RoundedCornerShape(4.dp))
								.padding(horizontal = 6.dp, vertical = 2.dp),
						) {
							Text(
								text = "EXPORTING",
								style = typography.monoSmall.copy(fontSize = 9.sp, fontWeight = FontWeight.Bold),
								color = Color(0xFF4EC9B0),
							)
						}
					}
				}
				CompactIconButton(
					onClick = { viewModel.closeExportPsdDialog() },
					enabled = !isExporting,
					size = 20.dp,
				) {
					IconClose(modifier = Modifier.size(10.dp), tint = colors.textMuted)
				}
			}

			// Progress bar during export
			if (isExporting) {
				Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
					LinearProgressIndicator(
						progress = state.progress,
						modifier = Modifier.fillMaxWidth().height(4.dp),
						color = colors.accent,
						backgroundColor = colors.inputBackground,
					)
					Text(
						text = state.statusText,
						style = typography.caption.copy(fontSize = 10.sp),
						color = colors.accent,
						maxLines = 1,
						overflow = TextOverflow.Ellipsis,
					)
				}
			}

			// Destination File Section
			Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
				Text(
					text = tr("exportPsd.destinationFile"),
					style = typography.caption.copy(fontWeight = FontWeight.SemiBold, fontSize = 10.5.sp),
					color = colors.textPrimary,
				)
				Row(
					modifier = Modifier.fillMaxWidth(),
					verticalAlignment = Alignment.CenterVertically,
					horizontalArrangement = Arrangement.spacedBy(6.dp),
				) {
					Box(
						modifier = Modifier
							.weight(1f)
							.height(28.dp)
							.background(colors.inputBackground, RoundedCornerShape(4.dp))
							.border(BorderStroke(1.dp, colors.border), RoundedCornerShape(4.dp))
							.padding(horizontal = 8.dp),
						contentAlignment = Alignment.CenterStart,
					) {
						Text(
							text = targetPathString,
							style = typography.monoSmall.copy(fontSize = 10.5.sp),
							color = colors.textPrimary,
							maxLines = 1,
							overflow = TextOverflow.Ellipsis,
						)
					}
					CompactButton(
						text = tr("exportPsd.browse"),
						isPrimary = false,
						enabled = !isExporting,
						onClick = {
							val chosen = NativeFilePicker.chooseSavePsdFile(
								window = window,
								defaultName = computeDefaultFileName(selectedScale),
								initialDir = sourceParentDir,
							)
							if (!chosen.isNullOrBlank()) {
								targetPathString = chosen
							}
						},
					)
				}
			}

			// Resolution / Scale Section
			Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
				Text(
					text = tr("exportPsd.resolutionScale"),
					style = typography.caption.copy(fontWeight = FontWeight.SemiBold, fontSize = 10.5.sp),
					color = colors.textPrimary,
				)
				Row(horizontalArrangement = Arrangement.spacedBy(16.dp)) {
					listOf(1, 2, 4).forEach { scale ->
						val isSelected = selectedScale == scale
						Row(
							verticalAlignment = Alignment.CenterVertically,
							horizontalArrangement = Arrangement.spacedBy(6.dp),
							modifier = Modifier
								.clickable(enabled = !isExporting) {
									selectedScale = scale
									val defaultName = computeDefaultFileName(scale)
									targetPathString = if (sourceParentDir != null) Path.of(sourceParentDir, defaultName).toString() else defaultName
								},
						) {
							Box(
								modifier = Modifier
									.size(14.dp)
									.clip(RoundedCornerShape(7.dp))
									.border(BorderStroke(1.5.dp, if (isSelected) colors.accent else colors.border), RoundedCornerShape(7.dp))
									.padding(3.dp),
								contentAlignment = Alignment.Center,
							) {
								if (isSelected) {
									Box(
										modifier = Modifier
											.fillMaxSize()
											.clip(RoundedCornerShape(4.dp))
											.background(colors.accent),
									)
								}
							}
							Text(
								text = if (scale == 1) tr("exportPsd.scale1x") else tr("exportPsd.scaleNx", scale),
								style = typography.body.copy(fontSize = 11.sp),
								color = if (isSelected) colors.textPrimary else colors.textMuted,
							)
						}
					}
				}
			}

			// Model info preview
			Box(
				modifier = Modifier
					.fillMaxWidth()
					.background(colors.inputBackground, RoundedCornerShape(4.dp))
					.border(BorderStroke(1.dp, colors.border), RoundedCornerShape(4.dp))
					.padding(10.dp),
			) {
				Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
					Row(
						modifier = Modifier.fillMaxWidth(),
						horizontalArrangement = Arrangement.SpaceBetween,
					) {
						Text(
							text = tr("exportPsd.canvasDimensions"),
							style = typography.caption.copy(fontSize = 10.sp),
							color = colors.textMuted,
						)
						Text(
							text = "${canvasW} × ${canvasH} px",
							style = typography.monoSmall.copy(fontSize = 10.sp, fontWeight = FontWeight.SemiBold),
							color = colors.accent,
						)
					}
					Row(
						modifier = Modifier.fillMaxWidth(),
						horizontalArrangement = Arrangement.SpaceBetween,
					) {
						Text(
							text = tr("exportPsd.layerCount"),
							style = typography.caption.copy(fontSize = 10.sp),
							color = colors.textMuted,
						)
						Text(
							text = "$layerCount",
							style = typography.monoSmall.copy(fontSize = 10.sp, fontWeight = FontWeight.SemiBold),
							color = colors.textPrimary,
						)
					}
				}
			}

			// Include generated layers checkbox
			Column(verticalArrangement = Arrangement.spacedBy(2.dp)) {
				CompactCheckbox(
					checked = includeGenerated,
					onCheckedChange = { includeGenerated = it },
					label = tr("exportPsd.includeGenerated"),
					enabled = !isExporting,
				)
				Text(
					text = tr("exportPsd.includeGeneratedDesc"),
					style = typography.caption.copy(fontSize = 9.5.sp),
					color = colors.textMuted,
					modifier = Modifier.padding(start = 22.dp),
				)
			}

			// Footer Buttons
			Row(
				modifier = Modifier.fillMaxWidth().padding(top = 4.dp),
				horizontalArrangement = Arrangement.End,
				verticalAlignment = Alignment.CenterVertically,
			) {
				CompactButton(
					text = tr("exportPsd.cancel"),
					isPrimary = false,
					enabled = !isExporting,
					onClick = { viewModel.closeExportPsdDialog() },
				)
				Spacer(Modifier.width(8.dp))
				CompactButton(
					text = tr("exportPsd.export"),
					isPrimary = true,
					enabled = !isExporting && targetPathString.isNotBlank(),
					onClick = {
						val target = runCatching { Path.of(targetPathString) }.getOrNull()
						if (target != null) {
							viewModel.exportPsd(target, selectedScale, includeGenerated)
						}
					},
				)
			}
		}
	}
}
